version: '3.8'

services: #Rust Gateway

  gateway:

    build:
      context: ./gateway          
      dockerfile: Dockerfile      #TODO: Implement Dockerfile to fix this
    ports:
      - "80:8080"
    labels:
      coolify.managed: "true"
      coolify.git: "true"
    environment:
      - RUST_LOG=info
      - PORT=8080
    restart: unless-stopped

  #static HTML

  frontend:
    build:
      context: ./frontend         
      dockerfile: Dockerfile      
    ports:
      - "3000:80"
    labels:
      coolify.managed: "true"
      coolify.git: "true"
    restart: unless-stopped

  #go
  
  go-tool:
    build:
      context: ./go-tool
      dockerfile: Dockerfile
    ports:
      -"8081:8080"
    labels:
      coolify.managed: "true"
      coolify.git: "true"
    restart: unless-stopped
 
  #python
  
  python-tool:
    build:
      context: ./python-tool
      dockerfile: Dockerfile
    ports:
      -"5000:5000"
    labels:
      coolify.managed: "true"
      coolify.git: "true"
    restart: unless-stopped
 
  #julia
  
  julia-tool:
    build:
      context: ./julia-tool
      dockerfile: Dockerfile
    ports:
      -"8000:8000"
    labels:
      coolify.managed: "true"
      coolify.git: "true"
    restart: unless-stopped